#!/usr/bin/env bash
# scad-dep-graph.sh — Generate per-project Mermaid dependency graphs from .scad include/use statements.
# Usage: bash scripts/scad-dep-graph.sh
# Each project directory with dependencies gets its own dependency-graph.md.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"

# Collect all .scad files, excluding .github and ideas directories
mapfile -t scad_files < <(
  find "$REPO_ROOT" -name '*.scad' \
    -not -path "$REPO_ROOT/.github/*" \
    -not -path "$REPO_ROOT/ideas/*" \
    | sort
)

# Build a map of project dirs (first path component relative to repo root)
declare -A file_project   # filepath -> project dir
declare -A file_basename   # filepath -> basename
declare -A node_id         # filepath -> sanitized mermaid node id
declare -A projects        # project dir -> 1

# Track which files are used as include/use targets (libraries)
declare -A is_library

# Edges: source_path -> "type:target_path" (newline-separated)
declare -A edges

for f in "${scad_files[@]}"; do
  rel="${f#"$REPO_ROOT/"}"
  project="$(echo "$rel" | cut -d/ -f1)"
  base="$(basename "$f")"

  file_project["$f"]="$project"
  file_basename["$f"]="$base"
  projects["$project"]=1

  # Sanitize node ID: basename with non-alnum replaced by _
  sanitized="$(echo "${base%.scad}" | sed 's/[^a-zA-Z0-9]/_/g')"
  node_id["$f"]="$sanitized"

  # Parse include/use statements
  while IFS= read -r line; do
    dep_type="$(echo "$line" | sed -n 's/^[[:space:]]*\(include\|use\)[[:space:]]\+<\(.*\)>.*/\1/p')"
    dep_target="$(echo "$line" | sed -n 's/^[[:space:]]*\(include\|use\)[[:space:]]\+<\(.*\)>.*/\2/p')"

    if [[ -n "$dep_type" && -n "$dep_target" ]]; then
      # Resolve target relative to source file's directory
      src_dir="$(dirname "$f")"
      target_path="$src_dir/$dep_target"

      if [[ -f "$target_path" ]]; then
        is_library["$target_path"]=1
        edges["$f"]+="${dep_type}:${target_path}"$'\n'
      fi
    fi
  done < <(grep -E '^\s*(include|use)\s+<' "$f" 2>/dev/null || true)
done

# Emit per-project dependency graph files
for project in $(printf '%s\n' "${!projects[@]}" | sort); do
  # Collect files in this project
  project_files=()
  for f in "${scad_files[@]}"; do
    if [[ "${file_project[$f]}" == "$project" ]]; then
      project_files+=("$f")
    fi
  done

  # Check if this project has any edges
  has_edges=false
  for f in "${project_files[@]}"; do
    if [[ -n "${edges[$f]:-}" ]]; then
      has_edges=true
      break
    fi
  done

  # Skip projects with no dependencies
  if [[ "$has_edges" == false ]]; then
    # Remove stale dependency-graph.md if it exists
    rm -f "$REPO_ROOT/$project/dependency-graph.md"
    continue
  fi

  outfile="$REPO_ROOT/$project/dependency-graph.md"

  {
    cat <<HEADER
# Dependency Graph

> Auto-generated by \`scripts/scad-dep-graph.sh\` — do not edit manually.
>
> Regenerate: \`bash scripts/scad-dep-graph.sh\`

Library files use rounded nodes; renderable files use square nodes.
Edges are labeled \`include\` or \`use\`.

\`\`\`mermaid
graph TD
HEADER

    # Emit nodes — libraries get stadium shape ([...]), renderables get square [...]
    for f in "${project_files[@]}"; do
      nid="${node_id[$f]}"
      label="${file_basename[$f]}"
      if [[ -n "${is_library[$f]:-}" ]]; then
        echo "  ${nid}([\"${label}\"])"
      else
        echo "  ${nid}[\"${label}\"]"
      fi
    done

    # Emit edges
    for f in "${project_files[@]}"; do
      if [[ -n "${edges[$f]:-}" ]]; then
        while IFS= read -r edge; do
          [[ -z "$edge" ]] && continue
          dep_type="${edge%%:*}"
          target="${edge#*:}"
          echo "  ${node_id[$f]} -->|${dep_type}| ${node_id[$target]}"
        done <<< "${edges[$f]}"
      fi
    done

    echo '```'
  } > "$outfile"

  echo "Generated $project/dependency-graph.md"
done
